[package]
name = "vcmi_launcher_v2"
version = "@VCMI_VERSION_MAJOR@.@VCMI_VERSION_MINOR@.@VCMI_VERSION_PATCH@"
edition = "2021"
resolver = "2"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
image = { version = "0.24", features = ["png"] }
egui = { version = "0.23" }
egui_extras = { version = "0.23", features = ["all_loaders"] }
eframe = { version = "0.23", default-features = false, features = [
    "accesskit",
    "default_fonts",
    # "glow",
    "wgpu",
    "android-game-activity",
] }
# egui-toast = "0.9.0"                        # in app notifications
egui-toast = { git = "https://github.com/PingPongun/egui-toast.git", branch = "egui_23" } # in app notifications

winit = { version = "0.28.6", features = ["android-game-activity"] }
rfd = { version = "0.12.0", optional = true }                        # file dialog

zip = "0.6.6"
rust-i18n = { git = "https://github.com/PingPongun/rust-i18n.git", branch = "develop" }
reqwest = { version = "0.11.18", features = ["json"] }                                  # http
tokio = { version = "1.31.0", features = ["rt-multi-thread"] }                          # async

serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
serde_plain = "1.0.2"
# serde-enum-str = "0.4.0"

# strum = { version = "0.25.0", features = ["derive"] }
strum = { git = "https://github.com/PingPongun/strum.git", branch = "master", features = [
    "derive",
] } # enum derive macros
atomic_enum = "0.2.0"
vcmi_launcher_macros = { path = "macros/" }
directories = "5.0.1"
sys-locale = "0.3.0" #detect system locale
lazy_static = "1.4.0"
# font-kit = "0.11.0" #load system fonts
educe = "0.4.22"    # struct derive macros
fs_extra = "1.3.0"  # copy dirs
os_info = "3.7.0"
fern = "0.6.2"      #logging crate
humantime = "2.1.0"
# tempfile = "3.8.0"                            #temp data management
indexmap = "2.0.0"     #ordered hash map
parking_lot = "0.12.1" #synchronization primitives

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.1"                               # logging backend for android
jni = { version = "0.21.1", features = ["invocation"] }
ndk-context = "0.1.1"

[build-dependencies]
embed-resource = "2.3.0"
cc = "1.0.83"
git-sha1 = { version = "1.1", optional = true }

# [patch.crates-io]
# egui = { git = "https://github.com/emilk/egui", branch = "master" }
# egui_extras = { git = "https://github.com/emilk/egui", branch = "master" }
# eframe = { git = "https://github.com/emilk/egui", branch = "master" }

[features]
default = [@VCMI_CARGO_FEATURES_DEFAULT@] 
desktop = ["dep:rfd"]
enable_gitversion = ["dep:git-sha1"]

[lib]
path = "src/main.rs"
name = "vcmilauncherv2lib"
crate_type = ["cdylib", "staticlib"]

[[bin]]
path = "src/main.rs"
name = "vcmilauncherv2"
required-features = ["desktop"]

[profile.release]
opt-level = 3
lto = "thin"      # Enable link time optimization
strip = true      # Automatically strip symbols from the binary.
codegen-units = 4 # Reduce parallel code generation units

[profile.MinSizeRel]
inherits = "release"
opt-level = "s"
lto = "thin"
strip = true
codegen-units = 4

[profile.RelWithDebInfo]
inherits = "dev"
opt-level = 2            #
debug = true
debug-assertions = false #
overflow-checks = false  #
lto = false
panic = 'unwind'
incremental = true
codegen-units = 32       #

[profile.MinSizeRel.package."*"]
opt-level = "s"
